### ISSUE TITLE
How to Implement Real-Time Post Fetching from Facebook Groups Using Webhooks?

### ISSUE THREAD

**Issue by amen160** [huandu/facebook#209] opened 2023-03-27 06:03 UTC
I would like to implement a real-time feature to fetch posts from a Facebook group, which means that my server will receive the post data immediately when a user posts something in the group. Although I have read about webhooks, I cannot find any documentation related to groups.

**Comment by huandu** [comment] 2023-03-27 06:35
Can you please let me know which facebook API you are using?

**Comment by huandu** [comment] 2023-04-01 11:56
@amen160 I read the document for [Subscriptions Edge from web hook](https://developers.facebook.com/docs/graph-api/webhooks/subscriptions-edge). It seems you can create subscription for any graph object.

**Comment by Jornalist** [comment] 2023-06-23 18:39
It’s been one month since my monitization program on my page has been stopped working with out any wrong doing . I’m still in shock as it was the only source of my income . I study a university and what I earn from my page is used to pay the tuition fee. 

Please if you could take a second look into this matter I really appreciate it . https://www.facebook.com/Wariye.Carab

**Comment by Jornalist** [comment] 2023-06-23 18:43
Dear Mohamud,

 

Please kindly note that monetization is not within the scope of issues I am able to assist with. There is however a link that you can go to that was shared with me, to appeal any issues you are having with monetization here: https://www.facebook.com/business/help/304874908436039?id=2520940424820218

 

I hope this helps.

**Comment by Jornalist** [comment] 2023-06-23 18:43
Hi Mohamud , 

I hope you are doing good! 

Your case number is 650135029898820. My name is Sheryl and I am happy to assist you regarding the matter. 

As already informed you that we have checked and can see that monetization has been disabled and it will be enabled when the Page is continuously following all the policy guidelines. I will also try to get this fixed as soon as possible. No you won't be receiving any replies from our end as we are investigating it for and you will receive the update once the restriction is uplifted. 

You can go through the policies: 
https://www.facebook.com/business/help/1348682518563619 

If you have any other questions, you can always contact us back. You can open a new case through the following link: https://www.facebook.com/business/help/support 

Thank you for contacting Meta Support Pro! We wish you and your business well. 

Thanks, 
Sheryl

**Comment by Jornalist** [comment] 2023-06-23 18:49
https://business.facebook.com/latest/monetization/monetization_home/monetization_home_main?nav_ref=media_manager_redirect_home

**Comment by Jornalist** [comment] 2023-06-23 18:49
![IMG_1223](https://github.com/huandu/facebook/assets/137540900/ed0375f7-aa45-47d6-b1e0-3d8b3d3401a1)

**Comment by huandu** [comment] 2023-07-22 15:54
I don't have any experience in running monetization program. I'm afraid that I cannot give you any valuable suggestion for your issue.

I'm closing this issue as the issue is beyond the scope of this package. Feel free to open issue to me if you have troubles when using this package.

**Closed by huandu** 2023-07-22 15:54 UTC
Labels: question
